{% set version = "15.0.0" %}

package:
  name: ripgrep
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/ripgrep/archive/{{ version }}.tar.gz
  sha256: e6b2d35ff79c3327edc0c92a29dc4bb74e82d8ee4b8156fb98e767678716be7a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - asciidoctor                      # [not win]

test:
  commands:
    - rg --help

about:
  home: https://github.com/BurntSushi/ripgrep
  license: MIT
  summary: ripgrep recursively searches directories for a regex pattern
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dbast
    - seanyen
