{% set version = "15.1.0" %}

package:
  name: ripgrep
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/ripgrep/archive/{{ version }}.tar.gz
  sha256: 046fa01a216793b8bd2750f9d68d4ad43986eb9c0d6122600f993906012972e8

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
    - asciidoctor                      # [not win]

test:
  commands:
    - rg --help

about:
  home: https://github.com/BurntSushi/ripgrep
  license: MIT
  summary: ripgrep recursively searches directories for a regex pattern
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dbast
    - seanyen
